# Generated by Django 4.2.7 on 2023-12-06 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cosecha', models.SmallIntegerField()),
                ('pais', models.CharField(max_length=30)),
                ('region', models.CharField(max_length=30, null=True)),
                ('designacion', models.CharField(blank=True, max_length=30, null=True)),
                ('puntos', models.SmallIntegerField()),
                ('precio', models.FloatField()),
                ('provincia', models.CharField(max_length=30, null=True)),
                ('nombre', models.CharField(max_length=30)),
                ('cepas', models.CharField(max_length=15)),
                ('bodega', models.CharField(max_length=50)),
                ('stock', models.SmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'vinoteca',
            },
        ),
    ]
